### ISSUE TITLE
Example Does not compile IDE 2

### ISSUE THREAD

**Issue by markrob1066** [shunceyb/MultiMAX6675#1]
The example sketch does not compile with a standard nano board selected.  Seems to be unable to find the #include <vector>  library.  Do I need to add this?

**Comment by shunceyb** [comment]
Sorry, I'll fix it right away.

**Comment by shunceyb** [comment]
Please test with the new version, 0.1.2, and please let me know if it works or not. It takes a few hours for this to refresh in the arduino library registry, so I guess you can just import the library first, downloaded from here.

https://docs.arduino.cc/software/ide-v1/tutorials/installing-libraries/

**Comment by markrob1066** [comment]
Hi,

Thanks for the quick response!  Compiles and seems to be working fine.  
I was able to update from the library manager, so I guess its fully live 
now.

Regards,

MArk


------ Original Message ------
From "Shuncey Balba" ***@***.***>
To "shunceyb/MultiMAX6675" ***@***.***>
Cc "markrob1066" ***@***.***>; "Author" 
***@***.***>
Date 6/11/2024 1:50:49 AM
Subject Re: [shunceyb/MultiMAX6675] Example Does not compile IDE 2 
(Issue #1)
